window.Connectly={user:null};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function initials(name='User'){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function avatar(user,size=''){const cls=`avatar ${size}`.trim();return user?.avatarUrl?`<img class="${cls}" src="${escapeHTML(user.avatarUrl)}" alt="${escapeHTML(user.fullName)} avatar">`:`<div class="${cls}" aria-label="${escapeHTML(user?.fullName||'User')} avatar">${initials(user?.fullName)}</div>`;}
function timeAgo(date){const sec=Math.max(1,Math.floor((Date.now()-new Date(date))/1000));if(sec<60)return 'just now';const min=Math.floor(sec/60);if(min<60)return `${min}m`;const h=Math.floor(min/60);if(h<24)return `${h}h`;const d=Math.floor(h/24);if(d<7)return `${d}d`;return new Date(date).toLocaleDateString(undefined,{month:'short',day:'numeric'});}
function toast(message,type=''){let wrap=$('.toast-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='toast-wrap';document.body.append(wrap)}const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;wrap.append(el);setTimeout(()=>el.remove(),3300)}
async function getMe(redirect=true){try{const d=await API.get('/auth/me');Connectly.user=d.user;return d.user}catch(e){if(redirect&&e.status===401)location.href='/login.html';throw e}}
function navItem(href,icon,label,key){const active=document.body.dataset.page===key?'active':'';return `<a class="nav-link ${active}" href="${href}"><span class="ico">${icon}</span><span>${label}</span></a>`}
function mountChrome(user){
 const left=$('#leftbar');if(left)left.innerHTML=`<div class="brand" style="padding:0 14px 14px"><img src="/assets/logo.svg" alt=""><span>Connectly</span></div><nav class="card nav-panel">${navItem('/home.html','⌂','Home','home')}${navItem('/search.html','⌕','Discover','search')}${navItem('/notifications.html','♡','Notifications','notifications')}${navItem(`/profile.html?id=${user.id}`,'◎','Profile','profile')}<button class="nav-link" id="logoutBtn" style="border:0;background:transparent;width:100%;text-align:left"><span class="ico">↪</span><span>Logout</span></button></nav><a href="/profile.html?id=${user.id}" class="card sidebar-profile">${avatar(user,'sm')}<span class="meta"><strong>${escapeHTML(user.fullName)}</strong><span class="muted small">@${escapeHTML(user.username)}</span></span></a>`;
 const right=$('#rightbar');if(right)right.innerHTML=`<div class="card right-panel"><h3>Connectly tip</h3><p class="muted small" style="margin:0">Build a thoughtful network. Follow people whose ideas help you learn, create, and grow.</p></div><div class="card right-panel"><h3>Trending topics</h3><div class="small"><p><strong>#BuildInPublic</strong><br><span class="muted">Design · Development</span></p><p><strong>#CreativeProcess</strong><br><span class="muted">Community</span></p><p><strong>#CareerGrowth</strong><br><span class="muted">Professional</span></p></div></div>`;
 const mobile=$('#mobileNav');if(mobile)mobile.innerHTML=`<a href="/home.html" class="${document.body.dataset.page==='home'?'active':''}" aria-label="Home">⌂</a><a href="/search.html" class="${document.body.dataset.page==='search'?'active':''}" aria-label="Search">⌕</a><a href="/home.html#composer" aria-label="Create post">⊕</a><a href="/notifications.html" class="${document.body.dataset.page==='notifications'?'active':''}" aria-label="Notifications">♡</a><a href="/profile.html?id=${user.id}" class="${document.body.dataset.page==='profile'?'active':''}" aria-label="Profile">◎</a>`;
 const mt=$('#mobileTop');if(mt)mt.innerHTML=`<a class="brand" href="/home.html"><img src="/assets/logo.svg" alt=""><span>Connectly</span></a><a href="/profile.html?id=${user.id}">${avatar(user,'sm')}</a>`;
 $('#logoutBtn')?.addEventListener('click',async()=>{await API.post('/auth/logout',{});location.href='/login.html'});
}
async function bootApp(){const user=await getMe();mountChrome(user);document.dispatchEvent(new CustomEvent('connectly:ready',{detail:{user}}));}
window.$=$;window.$$=$$;window.escapeHTML=escapeHTML;window.avatar=avatar;window.timeAgo=timeAgo;window.toast=toast;window.getMe=getMe;
if(document.body.dataset.authRequired==='true')bootApp().catch(()=>{});
