const express=require('express');const path=require('path');const helmet=require('helmet');const cors=require('cors');const cookieParser=require('cookie-parser');const rateLimit=require('express-rate-limit');const env=require('./config/env');const {notFound,errorHandler}=require('./middleware/error');
const app=express();
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(cors({origin:env.corsOrigin,credentials:true}));
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true,limit:'1mb'}));app.use(cookieParser());
app.use('/api/auth',rateLimit({windowMs:15*60*1000,limit:100,standardHeaders:'draft-8',legacyHeaders:false}));
app.use('/uploads',express.static(path.join(process.cwd(),'server','uploads'),{maxAge:'1d'}));
app.use('/api/auth',require('./routes/auth.routes'));app.use('/api/users',require('./routes/users.routes'));app.use('/api/posts',require('./routes/posts.routes'));app.use('/api/comments',require('./routes/comments.routes'));app.use('/api/notifications',require('./routes/notifications.routes'));
app.get('/api/health',(_req,res)=>res.json({status:'ok',app:'Connectly'}));
app.use(express.static(path.join(process.cwd(),'client'),{extensions:['html']}));
app.use(notFound);app.use(errorHandler);module.exports=app;
